Code Refactoring for optimization
deye9/foodie pull request #6
Opened 2024-03-21 23:13 UTC by deye9

2024-03-23 20:00 UTC, sfagade requested changes
Can you please make next PR smaller?

2024-03-25 08:35 UTC, deye9 commented on libraries/src/main/java/com/foodie/kafka/config/KafkaConfig.java
> +// import static org.apache.kafka.streams.StreamsConfig.APPLICATION_ID_CONFIG;
Still working on this.

2024-03-25 08:35 UTC, deye9 commented on libraries/src/main/java/com/foodie/kafka/service/KafkaConsumerService.java
> +                System.out.printf("offset = %d, key = %s, value = %s%n", record.offset(),
Error from my side

2024-03-25 08:36 UTC, deye9 commented on libraries/src/main/java/com/foodie/kafka/config/KafkaConfig.java
> +        KafkaAdmin kafkaAdmin = new KafkaAdmin(kafkaProperties.buildAdminProperties());
Working on the fix

2024-03-25 08:37 UTC, deye9 commented on services/user-management/src/main/java/com/foodie/user/controllers/AuthenticationController.java
> +    private AuthenticationService service;
It was breaking the code

2024-03-25 08:37 UTC, deye9 commented on services/user-management/src/main/java/com/foodie/user/service/RoleService.java
> +public class RoleService implements FoodieBaseService<Role, UUID> {
Magic

2024-03-25 08:46 UTC, merged